insert into users (first_name, last_name, phone_number, email) values ('Conny', 'Smorthit', '2739444360', 'csmorthit0@cam.ac.uk');
insert into users (first_name, last_name, phone_number, email) values ('Tobe', 'Kensall', '3478347582', 'tkensall1@opensource.org');
insert into users (first_name, last_name, phone_number, email) values ('Genvieve', 'Brazear', '9438993159', 'gbrazear2@huffingtonpost.com');
insert into users (first_name, last_name, phone_number, email) values ('Anthea', 'Brisbane', '7375686015', 'abrisbane3@bloglines.com');
insert into users (first_name, last_name, phone_number, email) values ('Gerek', 'Wormleighton', '1878766383', 'gwormleighton4@alexa.com');
insert into users (first_name, last_name, phone_number, email) values ('Dori', 'Daborn', '6041857098', 'ddaborn5@sitemeter.com');
insert into users (first_name, last_name, phone_number, email) values ('Corrinne', 'Etherson', '3686285872', 'cetherson6@upenn.edu');
insert into users (first_name, last_name, phone_number, email) values ('Margareta', 'Tiron', '9708829068', 'mtiron7@globo.com');
insert into users (first_name, last_name, phone_number, email) values ('Latia', 'Le Barre', '7176044012', 'llebarre8@theglobeandmail.com');
insert into users (first_name, last_name, phone_number, email) values ('Christabel', 'Oda', '5778929733', 'coda9@berkeley.edu');